// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: grpc/email/proto/email.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PasswordCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *PasswordCodeReq) Reset() {
	*x = PasswordCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_email_proto_email_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordCodeReq) ProtoMessage() {}

func (x *PasswordCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_email_proto_email_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordCodeReq.ProtoReflect.Descriptor instead.
func (*PasswordCodeReq) Descriptor() ([]byte, []int) {
	return file_grpc_email_proto_email_proto_rawDescGZIP(), []int{0}
}

func (x *PasswordCodeReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PasswordCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PasswordCodeRes) Reset() {
	*x = PasswordCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_email_proto_email_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordCodeRes) ProtoMessage() {}

func (x *PasswordCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_email_proto_email_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordCodeRes.ProtoReflect.Descriptor instead.
func (*PasswordCodeRes) Descriptor() ([]byte, []int) {
	return file_grpc_email_proto_email_proto_rawDescGZIP(), []int{1}
}

type SupportMessageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SupportMessageReq) Reset() {
	*x = SupportMessageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_email_proto_email_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportMessageReq) ProtoMessage() {}

func (x *SupportMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_email_proto_email_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportMessageReq.ProtoReflect.Descriptor instead.
func (*SupportMessageReq) Descriptor() ([]byte, []int) {
	return file_grpc_email_proto_email_proto_rawDescGZIP(), []int{2}
}

func (x *SupportMessageReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SupportMessageRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SupportMessageRes) Reset() {
	*x = SupportMessageRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_email_proto_email_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupportMessageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupportMessageRes) ProtoMessage() {}

func (x *SupportMessageRes) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_email_proto_email_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupportMessageRes.ProtoReflect.Descriptor instead.
func (*SupportMessageRes) Descriptor() ([]byte, []int) {
	return file_grpc_email_proto_email_proto_rawDescGZIP(), []int{3}
}

var File_grpc_email_proto_email_proto protoreflect.FileDescriptor

var file_grpc_email_proto_email_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x73, 0x72, 0x63, 0x22, 0x3b, 0x0a, 0x0f, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x11, 0x0a, 0x0f, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x32, 0x98, 0x01, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64,
	0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x2e, 0x73,
	0x72, 0x63, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x14, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x12, 0x53, 0x65,
	0x6e, 0x64, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x16, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x73, 0x72, 0x63, 0x2e, 0x53,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_email_proto_email_proto_rawDescOnce sync.Once
	file_grpc_email_proto_email_proto_rawDescData = file_grpc_email_proto_email_proto_rawDesc
)

func file_grpc_email_proto_email_proto_rawDescGZIP() []byte {
	file_grpc_email_proto_email_proto_rawDescOnce.Do(func() {
		file_grpc_email_proto_email_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_email_proto_email_proto_rawDescData)
	})
	return file_grpc_email_proto_email_proto_rawDescData
}

var file_grpc_email_proto_email_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpc_email_proto_email_proto_goTypes = []interface{}{
	(*PasswordCodeReq)(nil),   // 0: src.PasswordCodeReq
	(*PasswordCodeRes)(nil),   // 1: src.PasswordCodeRes
	(*SupportMessageReq)(nil), // 2: src.SupportMessageReq
	(*SupportMessageRes)(nil), // 3: src.SupportMessageRes
}
var file_grpc_email_proto_email_proto_depIdxs = []int32{
	0, // 0: src.EmailService.SendPasswordCode:input_type -> src.PasswordCodeReq
	2, // 1: src.EmailService.SendSupportMessage:input_type -> src.SupportMessageReq
	1, // 2: src.EmailService.SendPasswordCode:output_type -> src.PasswordCodeRes
	3, // 3: src.EmailService.SendSupportMessage:output_type -> src.SupportMessageRes
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_email_proto_email_proto_init() }
func file_grpc_email_proto_email_proto_init() {
	if File_grpc_email_proto_email_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_email_proto_email_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasswordCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_email_proto_email_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasswordCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_email_proto_email_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportMessageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_email_proto_email_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupportMessageRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_email_proto_email_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_email_proto_email_proto_goTypes,
		DependencyIndexes: file_grpc_email_proto_email_proto_depIdxs,
		MessageInfos:      file_grpc_email_proto_email_proto_msgTypes,
	}.Build()
	File_grpc_email_proto_email_proto = out.File
	file_grpc_email_proto_email_proto_rawDesc = nil
	file_grpc_email_proto_email_proto_goTypes = nil
	file_grpc_email_proto_email_proto_depIdxs = nil
}
